<h1>
    Audit Comparission
</h1>

<table  class="table table-striped table-hover table-bordered ">
    <caption>
        Comparing <a href="<?=

                    $this->url(
                        'audit/entity',
                        array(
                            'entityClass' => $this->auditService()->getAuditEntity($revisionEntity_old)->getAuditedEntityClass(),
                        )
                    );?>

        " class="btn btn-primary"><?php echo $this->escapeHtml($this->auditService()->getAuditEntity($revisionEntity_old)->getAuditedEntityClass()); ?></a>
        between

            <?= $this->auditRevisionEntityLink($revisionEntity_old); ?>

        and

            <?= $this->auditRevisionEntityLink($revisionEntity_new); ?>

    </caption>
    <thead>
        <tr>
            <th>Field</th>
            <th>Deleted</th>
            <th>Same</th>
            <th>Updated</th>
        </tr>
    </thead>
    <tbody>

        <?php
        $oldValues = $this->auditService()->getEntityValues($this->auditService()->getAuditEntity($revisionEntity_old));
        $newValues = $this->auditService()->getEntityValues($this->auditService()->getAuditEntity($revisionEntity_new));

        foreach ($oldValues as $field => $value) {
        ?>
            <tr>
                <td><?= $field; ?></td>
                <td>
                    <?php
                    if ($oldValues[$field] != $newValues[$field] && !$newValues[$field] && $oldValues[$field]) {
                        if ($oldValues[$field] instanceof DateTime) {
                            echo $this->auditDateTimeFormatter($oldValues[$field]);
                        } else {
                            echo $this->escapeHtml($oldValues[$field]);
                        }
                    }
                    ?>
                </td>
                <td>
                    <?php
                    if ($oldValues[$field] == $newValues[$field]) {
                        if ($oldValues[$field] instanceof DateTime) {
                            echo $this->auditDateTimeFormatter($oldValues[$field]);
                        } else {
                            echo $this->escapeHtml($oldValues[$field]);
                        }
                    }
                    ?>
                </td>
                <td>
                    <?php
                    if ($oldValues[$field] != $newValues[$field] && $newValues[$field]) {
                        if ($newValues[$field] instanceof DateTime) {
                            echo $this->auditDateTimeFormatter($newValues[$field]);
                        } else {
                            echo $this->escapeHtml($newValues[$field]);
                        }
                    }
                    ?>
                </td>
            </tr>
        <?php
        }
        ?>
    </tbody>
</table>

<table class="table table-striped table-hover table-bordered ">
    <caption>
        Old
    </caption>
    <thead>
        <tr>
            <td>
                <a href="<?=
                    $this->url('audit/revisions',
                        array(
                            'revisionId' => $revisionEntity_old->getRevision()->getId()
                        )
                    );
                ?>">

                    <?= $this->escapeHtml($revisionEntity_old->getRevision()->getId());?>
                    @ <?php echo $this->auditDateTimeFormatter($revisionEntity_old->getRevision()->getTimestamp()); ?>

                </a>


            </td>

            <td>
                <?= $this->auditRevisionEntityLink($revisionEntity_old); ?>
           </td>

        </tr>

        <tr>
            <th>Field</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->auditService()->getEntityValues($this->auditService()->getAuditEntity($revisionEntity_old)) as $field => $value): ?>
            <tr>
                <td><?php  echo $this->escapeHtml($field); ?></td>
                <td>
                    <?php if ($value instanceof DateTime): ?>
                        <?php echo  $this->auditDateTimeFormatter($value); ?>
                    <?php else : ?>
                        <?php  echo $this->escapeHtml($value); ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>

<table class="table table-striped table-hover table-bordered ">
    <caption>
        New
    </caption>

    <thead>
        <tr>
            <td>
                <a href="<?=
                    $this->url('audit/revisions',
                        array(
                            'revisionId' => $revisionEntity_old->getRevision()->getId()
                        )
                    );
                ?>">

                    <?= $this->escapeHtml($revisionEntity_old->getRevision()->getId());?>
                    @ <?php echo $this->auditDateTimeFormatter($revisionEntity_old->getRevision()->getTimestamp()); ?>

                </a>


            </td>
            <td>
                <?= $this->auditRevisionEntityLink($revisionEntity_new); ?>
            </td>
        </tr>
        <tr>
            <th>Field</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($this->auditService()->getEntityValues($this->auditService()->getAuditEntity($revisionEntity_new)) as $field => $value): ?>
            <tr>
                <td><?php  echo $this->escapeHtml($field); ?></td>
                <td>
                    <?php if ($value instanceof DateTime): ?>
                        <?php echo  $this->auditDateTimeFormatter($value); ?>
                    <?php else : ?>
                        <?php  echo $this->escapeHtml($value); ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
