<span class="pull-right">
    <a href="#" class="btn btn-success">Insert</a>
    <a href="#" class="btn btn-warning">Update</a>
    <a href="#" class="btn btn-danger">Delete</a>
</span>

<h1>Audit</h1>

<?php $paginator = $this->auditRevisionPaginator($this->page); ?>

<table class="table table-striped table-hover table-bordered">
    <thead>
        <tr>
            <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'zf-doctrine-audit/pagination/revision', array('route' => 'audit/page'));
            ?>
            </th>
        </tr>
        <tr>
            <th>Revision</th>
            <th>Entity</th>
            <th>Comment</th>
            <th>User</th>
        </tr>
    </thead>

    <tfoot>
        <th colspan="4">
            <?php echo $this->paginationControl($paginator,
                'Sliding',
                'zf-doctrine-audit/pagination/revision', array('route' => 'audit/page'));
            ?>
        </th>
    </tfoot>
    <tbody>
    <?php
    foreach ($paginator as $revision) {
    ?>
        <tr>
            <td>
                <a href="<?=
                    $this->url('audit/revisions',
                        array(
                            'revisionId' => $revision->getId()
                        )
                    );
                ?>">

                    <?= $this->escapeHtml($revision->getId());?>
                    @ <?php echo $this->auditDateTimeFormatter($revision->getTimestamp()); ?>

                </a>
            </td>

            <td>
            <?php
            $count = 0;
            foreach ($revision->getRevisionEntities() as $revisionEntity) {
                $count ++;
            ?>
                <div>
                    <?= $this->auditRevisionEntityLink($revisionEntity); ?>
                </div>
            <?php

                if ($count == 25) {
                    echo '<a href="';
                    echo $this->url('audit/revisions',
                        array(
                            'revisionId' => $revision->getId()
                        )
                    );
                ?>"> See More...
                </a>
            </td>
                <?php
                    break;
                }
            }
            ?>
            </td>

            <td><?= $this->escapeHtml($revision->getComment()); ?></td>

            <td>
                <a href="<?php
                    if ($revision->getUser()) {
                        echo $this->url('audit/user', array('userId' => $revision->getUser()->getId()));
                    } else {
                        echo $this->url('audit/user', array('userId' => '0'));
                    }
                ?>" class="btn btn-default">
                    <?php
                        if ($revision->getUser()) {
                            echo $this->gravatar($revision->getUser()->getEmail(), array('img_size' => 24));
                            echo ' ';
                            echo $this->escapeHtml($revision->getUser()->getDisplayName());
                        } else {
                            echo $this->gravatar('anonymous@unknown.net', array('img_size' => 24));
                            echo ' Anonymous';
                        }
                    ?>
                </a>
            </td>
        </tr>
    <?php
    }
    ?>
    </tbody>
</table>
